apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-ca
  namespace: kubecodriver-system
  annotations:
    cert-manager.io/inject-ca-from: kubecodriver-system/collector-cert # Cert-manager will inject CA cert here
