apiVersion: kubecodriver.codriverlabs.ai/v1alpha1
kind: CoDriverTool
metadata:
  name: tcpdump-config
  namespace: kubecodriver-system
spec:
  name: "tcpdump"
  description: "Network packet capture using tcpdump"
  image: ghcr.io/codriverlabs/ce/kubecodriver-tcpdump:v1.1.0
  defaultArgs:
    - "-i"
    - "any"
  securityContext:
    runAsRoot: true
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
