apiVersion: kubecodriver.codriverlabs.ai/v1alpha1
kind: CoDriverJob
metadata:
  name: tcpdump-persistent-capture
spec:
  targets:
    labelSelector:
      matchLabels:
        app: web-server
  tool:
    name: "tcpdump"
    duration: "5m"
    args:
      - "tcp and not port 22"
  output:
    mode: "pvc"
    pvc:
      claimName: "tcpdump-storage"
      path: "/captures"
