apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codriverjob-viewer-role
rules:
- apiGroups:
  - kubecodriver.codriverlabs.ai
  resources:
  - codriverjobs
  - codrivertools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubecodriver.codriverlabs.ai
  resources:
  - codriverjobs/status
  - codrivertools/status
  verbs:
  - get
