apiVersion: kubecodriver.codriverlabs.ai/v1alpha1
kind: CoDriverTool
metadata:
  name: aperf-config
  namespace: kubecodriver-system
spec:
  name: "aperf"
  image: ghcr.io/codriverlabs/ce/kubecodriver-aperf:v1.1.0
  securityContext:
    allowPrivileged: false
    allowHostPID: false
    runAsRoot: true
    capabilities:
      add: ["SYS_PTRACE", "PERFMON", "SYS_ADMIN"]
      drop: ["ALL"]
  allowedNamespaces:
    - "production"
    - "staging"
    - "development"
    - "kubecodriver-test"
  description: "Advanced performance profiling tool for CPU and memory analysis"
  version: "v1.0.12"
  defaultArgs: ["--cpu", "--memory"]
