apiVersion: kubecodriver.codriverlabs.ai/v1alpha1
kind: CoDriverJob
metadata:
  name: aperf-ephemeral-example
  namespace: kubecodriver-test
spec:
  targets:
    labelSelector:
      matchLabels:
        app: nginx
    container: "main-container"
  tool:
    name: "aperf"
    duration: "30s"
    args:
      cpu: true
      memory: true
      output: "/tmp/profile.data"
  output:
    mode: "ephemeral"
